# API設定
[api]
openai_key = "" # OpenAIのAPIキー
google_key = "" # Google Cloud Vision APIのAPIキー
claude_key = "" # anthropicのAPIキー

# Hugging Face設定
[huggingface]
hf_username = "" # Hugging Faceのユーザー名
repo_name = "" # リポジトリ名
token = "" # Hugging FaceのAPIトークン

# ディレクトリ設定
[directories]
database = ""  # 画像databaseのパス (空の場合はカレントディレクトリの'Image_database.image_database.db'を使用)
dataset = ""  # 画像ディレクトリのパス
output = ""   # 出力ディレクトリのパス（空の場合はカレントディレクトリの'output'を使用）
edited_output = ""  # 編集済みデータセットのパス（空の場合はカレントディレクトリの'edited_output'を使用）
response_file = ""  # レスポンスファイルディレクトリのパス（空の場合はカレントディレクトリの'response_file'を使用）

# 画像処理設定
[image_processing]
target_resolution = 512 # 学習モデルの基準解像度 512, 768, 1024
realesrganer_upscale = false # 長編が基準解像度より小さい場合、Trueだとアップスケールする
realesrgan_model = "RealESRGAN_x4plus_anime_6B.pth" # アップスケールモデルのパス

# 生成設定
[generation]
batch_jsonl = false # バッチ処理用のjsonlファイルを生成する場合はTrue
start_batch = false # バッチ処理を開始する場合はTrue
single_image = true # 画像ごとに処理する場合はTrue

# オプション設定
[options]
generate_meta_clean = false # sd-scriptsのファインチューニング用のメタデータを生成する場合はTrue
cleanup_existing_tags = false # タグを生成せずに既存のタグをクーんナップする場合はTrue
join_existing_txt = true # 生成したタグを既存のタグと結合する場合はTrue

# プロンプト設定
[prompts]
main = """
As an AI assistant specializing in image analysis, your task is to provide detailed and objective annotations for each image.
For every image, please follow these guidelines:\n
   \n
   1. **Tags (30-50 comma-separated words):**\n
   - **Main Subjects:** Identify people, objects, and scenery present in the image without making assumptions beyond what is visible.\n
   - **Artistic Elements:** Note styles, compositions, color palettes, and other notable artistic features.\n
   - **Mood or Atmosphere:** Convey the general feeling or ambiance of the image.\n
   - **Visible Actions or Interactions:** Describe any actions or interactions happening in the image neutrally.\n
   - Use tag conventions similar to Danbooru without underscores (e.g., use "blonde hair" instead of "blonde_hair").\n
   - Avoid speculative or subjective interpretations.\n
   \n
   2. **Caption (1-2 sentences):**\n
   - Provide a brief, objective description summarizing the main content and actions depicted in the image.\n
   - Keep the description neutral and based solely on visible elements.\n\n3. **Score (1.00 to 10.00):**\n
   - Rate the overall quality and impact of the image on a scale from **1.00** (lowest) to **10.00** (highest).\n
   - Consider factors like composition, clarity, creativity, and emotional impact.\n
   \n
   **Formatting:**\n
   \n
   - Begin each section with the section title followed by a colon.\n
   - Use the following template for your response:\n
   \n
   ```\n
   tags: [comma-separated tags]\n
   \n
   caption: [Your 1-2 sentence description]\n
   \n
   score: [Your rating between 1.00 and 10.00]\n
   ```\n
   \n
   **Example Output:**\n
   \n
   ```\n
   tags: 1girl, blonde hair, blue eyes, school uniform, classroom, desk, textbook, pencil, studying, daylight, window, serious expression, detailed background, realistic style, soft lighting\n
   \n
   caption: A young student with blonde hair and blue eyes sits at a desk in a sunlit classroom, focusing intently on her textbook with a pencil in hand.\n
   \n
   score: 8.50\n
   ```\n
"""
additional = "Your additional prompt here."

[log]
level = "INFO"
file = "app.log"