# API設定
[api]
# APIキーを設定は .env ファイルに記載

# Hugging Face設定
[huggingface]
repo_name = "test00" # リポジトリ名
# ユーザー名とトークンは .env ファイルに記載

# ディレクトリ設定
[directories]
database = ""  # 画像databaseのパス (空の場合はカレントディレクトリの'Image_database.image_database.db'を使用)
dataset = ""  # 画像ディレクトリのパス
output = ""   # 出力ディレクトリのパス（空の場合はカレントディレクトリの'output'を使用）
edited_output = ""  # 編集済みデータセットのパス（空の場合はカレントディレクトリの'edited_output'を使用）
response_file = ""  # レスポンスファイルディレクトリのパス（空の場合はカレントディレクトリの'response_file'を使用）

# 画像処理設定
[image_processing]
target_resolution = 1024 # 学習モデルの基準解像度 512, 768, 1024
realesrganer_upscale = false # 長編が基準解像度より小さい場合、trueだとアップスケールする
realesrgan_model = "RealESRGAN_x4plus_anime_6B.pth" # アップスケールモデルのパス

# 生成設定
[generation]
batch_jsonl = false # バッチ処理用のjsonlファイルを生成する場合はtrue
start_batch = false # バッチ処理を開始する場合はtrue
single_image = true # 画像ごとに処理する場合はtrue

# オプション設定
[options]
generate_meta_clean = false # sd-scriptsのファインチューニング用のメタデータを生成する場合はtrue
cleanup_existing_tags = false # タグを生成せずに既存のタグをクーんナップする場合はtrue
join_existing_txt = true # 生成したタグを既存のタグと結合する場合はtrue

# プロンプト設定
[prompts]
additional = "Your additional prompt here."

[log]
level = "DEBUG"
file = "app.log"