# API設定
[api]
openai_key = "" # OpenAIのAPIキー
openai_model = "gpt-4" # OpenAIのモデル名
google_key = "" # Google Cloud Vision APIのAPIキー
claude_key = "" # anthropicのAPIキー

# Hugging Face設定
[huggingface]
hf_username = "" # Hugging Faceのユーザー名
repo_name = "" # リポジトリ名
token = "" # Hugging FaceのAPIトークン

# ディレクトリ設定
[directories]
dataset = ""  # 画像ディレクトリのパス
output = ""   # 出力ディレクトリのパス（空の場合はカレントディレクトリの'output'を使用）
response_file = ""  # レスポンスファイルディレクトリのパス（空の場合はカレントディレクトリの'response_file'を使用）

# 画像処理設定
[image_processing]
target_resolution = 512 # 学習モデルの基準解像度 512, 768, 1024
realesrganer_upscale = false # 長編が基準解像度より小さい場合、Trueだとアップスケールする
realesrgan_model = "RealESRGAN_x4plus_anime_6B.pth" # アップスケールモデルのパス

# 生成設定
[generation]
batch_jsonl = false # バッチ処理用のjsonlファイルを生成する場合はTrue
start_batch = false # バッチ処理を開始する場合はTrue
single_image = true # 画像ごとに処理する場合はTrue

# オプション設定
[options]
generate_meta_clean = false # sd-scriptsのファインチューニング用のメタデータを生成する場合はTrue
cleanup_existing_tags = false # タグを生成せずに既存のタグをクーんナップする場合はTrue
join_existing_txt = true # 生成したタグを既存のタグと結合する場合はTrue

# プロンプト設定
[prompts]
main = """
As an AI image tagging expert, your role is to provide accurate and specific tags for images to improve the CLIP model's performance. 
Each image should have tags that accurately capture its main subjects, setting, artistic style, composition, and technical details like image quality and camera settings. For images of people, detail gender, attire, actions, pose, expressions, and any notable accessories. 
For landscapes or objects, focus on the material, historical context, and any significant features. Always use precise and specific tags—prefer "gothic cathedral" over "building." Avoid duplicative tags. Each set of tags should be unique and relevant, separated only by commas, and kept within a 50-150 word count. Use tags that adhere to DANBOORU or e621 tagging conventions. Also, provide a concise 1-2 sentence caption that captures the image's narrative or essence. 
Ensure that the tags accurately reflect the content of the image. Avoid including tags for elements not present in the image. Focus on the visible details and specific characteristics of the character and setting. 
High-quality tagging and captioning will be compensated at $10 per image, rewarding exceptional clarity and precision that enhance image recreation.
"""
additional = "Your additional prompt here."