"""Generate docs/cli.md from CLI introspection specs."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from lorairo.cli.introspection import FieldSpec, ModelSpec, ToolSpec, iter_tool_specs  # noqa: E402

OUTPUT = ROOT / "docs" / "cli.md"


def _field_text(field: FieldSpec) -> str:
    required = "required" if field.required else "optional"
    default = f", default `{field.default}`" if field.default is not None else ""
    description = f" - {field.description}" if field.description else ""
    return f"- `{field.name}`: `{field.type}` ({required}{default}){description}"


def _model_section(model: ModelSpec) -> list[str]:
    lines = [f"**{model.role.title()} `{model.name}`**"]
    if model.description:
        lines.append("")
        lines.append(model.description)
    if model.fields:
        lines.append("")
        lines.extend(_field_text(field) for field in model.fields)
    return lines


def _tool_section(spec: ToolSpec) -> list[str]:
    lines = [
        f"### `{spec.path}`",
        "",
        spec.summary,
        "",
        f"- Read only: `{str(spec.read_only).lower()}`",
        f"- Side effects: {', '.join(f'`{effect}`' for effect in spec.side_effects)}",
        "",
        "#### Compact Introspection",
        "",
        "```bash",
        f"lorairo-cli --json describe \"{spec.path}\"",
        "```",
        "",
        "#### Models",
        "",
    ]
    for model in (*spec.inputs, *spec.outputs, *spec.errors):
        lines.extend(_model_section(model))
        lines.append("")
    if spec.search_schema is not None:
        lines.extend(
            [
                "#### JSON Schema",
                "",
                "This search-driven command exposes the public `ImageFilterCriteria` schema:",
                "",
                "```bash",
                f"lorairo-cli --json describe \"{spec.path}\" --schema json_schema",
                "```",
                "",
            ]
        )
    return lines


def render() -> str:
    lines = [
        "# LoRAIro CLI ドキュメント",
        "",
        "LoRAIro のコマンドラインインターフェース（CLI）。GUI なし環境でのデータセット管理、",
        "バッチ処理、プログラマティックアクセスを提供します。",
        "",
        "## インストール",
        "",
        "```bash",
        "uv sync",
        "lorairo-cli --help",
        "```",
        "",
        "## 基本的な使い方",
        "",
        "OpenAI Moderation で未評価画像に rating を付与する CLI 手順は",
        "[CLI Rating Preflight Workflow](cli-rating-preflight.md) を参照してください。",
        "",
        "```bash",
        "lorairo-cli --help",
        "lorairo-cli project --help",
        "lorairo-cli version",
        "lorairo-cli status",
        "```",
        "",
        "## Machine-Readable Introspection",
        "",
        "ADR 0059 に従い、introspection は既存 JSONL kind の `item` / `result` / `error`",
        "だけを使います。`tool` / `model` / `schema` は `item` payload の `type` フィールドです。",
        "",
        "```bash",
        "lorairo-cli --json list-commands",
        "lorairo-cli --json describe \"images update\"",
        "lorairo-cli --json describe \"annotate run\" --schema json_schema",
        "```",
        "",
        "`list-commands` は各コマンドを `kind:\"item\", type:\"tool\"` として出力し、",
        "`read_only` と `side_effects` を含めます。`describe` の既定 `compact` は",
        "`type:\"model\"` 行で入力・出力・エラーの簡易フィールドを返します。",
        "`--schema json_schema` は Pydantic 由来の公開スキーマを `type:\"schema\"` の",
        "`item` 行に包みます。検索駆動コマンドは公開フィルタ契約",
        "`ImageFilterCriteria` を晒しますが、生 SQL や DB スキーマは晒しません。",
        "",
        "## Command Reference",
        "",
        "> Generated by `scripts/generate_cli_docs.py`. Edit introspection specs, then regenerate.",
        "",
    ]
    for spec in iter_tool_specs():
        lines.extend(_tool_section(spec))
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    OUTPUT.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
