"""Add model metadata fields for annotation processing integration

Revision ID: 469833dd8bda
Revises: d1a2b3c4d5e6
Create Date: 2025-07-25 11:34:45.563689

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "469833dd8bda"
down_revision: str | None = "d1a2b3c4d5e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.add_column(sa.Column("api_model_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("estimated_size_gb", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("requires_api_key", sa.Boolean(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.drop_column("requires_api_key")
        batch_op.drop_column("estimated_size_gb")
        batch_op.drop_column("api_model_id")

    # ### end Alembic commands ###
