"""Add error_records table for error tracking

Revision ID: 8a994488196e
Revises: fda27f4584ec
Create Date: 2025-11-23 00:37:08.302293

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a994488196e"
down_revision: str | None = "fda27f4584ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "error_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.Column("operation_type", sa.String(), nullable=False),
        sa.Column("error_type", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=False),
        sa.Column("stack_trace", sa.String(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["image_id"], ["images.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("error_records", schema=None) as batch_op:
        batch_op.create_index("ix_error_records_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_error_records_operation_type", ["operation_type"], unique=False)
        batch_op.create_index("ix_error_records_resolved", ["resolved_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("error_records", schema=None) as batch_op:
        batch_op.drop_index("ix_error_records_resolved")
        batch_op.drop_index("ix_error_records_operation_type")
        batch_op.drop_index("ix_error_records_created_at")

    op.drop_table("error_records")
    # ### end Alembic commands ###
