"""Add upscaler_used column to processed_images table

Revision ID: d1a2b3c4d5e6
Revises: c9b242b21b87
Create Date: 2025-07-10 05:10:07.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d1a2b3c4d5e6"
down_revision = "c9b242b21b87"
branch_labels = None
depends_on = None


def upgrade():
    """Add upscaler_used column to processed_images table."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("processed_images", schema=None) as batch_op:
        batch_op.add_column(sa.Column("upscaler_used", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Remove upscaler_used column from processed_images table."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("processed_images", schema=None) as batch_op:
        batch_op.drop_column("upscaler_used")
    # ### end Alembic commands ###
